# Generated by Django 3.1.4 on 2021-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('amadeus_branded_fares', models.BooleanField(default=False)),
                ('api_username', models.CharField(default='trialaccount', max_length=40)),
                ('api_password', models.CharField(default='p#F91Snf#Pr3Yr', max_length=40)),
                ('style_group', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_iframe', models.BooleanField(default=True)),
                ('student_and_youth', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('pcc', models.CharField(default='2G3C', max_length=15)),
                ('provider', models.CharField(choices=[('1A', '1A'), ('1V', '1V'), ('1G', '1G'), ('1P', '1P')], default='1V', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('queue', models.CharField(default='01', max_length=40)),
            ],
            options={
                'db_table': 'data_source',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_booking', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
