# Generated by Django 3.1.4 on 2021-01-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_agency', to='teams.agency'),
        ),
        migrations.AddField(
            model_name='team',
            name='common_parameters',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_common_parameters', to='common.commonparameters'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasource', to='teams.agency'),
        ),
        migrations.AddField(
            model_name='agency',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agency',
            name='common_parameters',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_common_parameters', to='common.commonparameters'),
        ),
    ]
