# Generated by Django 3.1.4 on 2021-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booking_endpoint',
            field=models.CharField(choices=[('prod', 'prod'), ('preprod', 'preprod')], default='preprod', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_endpoint',
            field=models.CharField(choices=[('prod', 'prod'), ('preprod', 'preprod')], default='preprod', max_length=8),
        ),
    ]
