# Generated by Django 3.1.4 on 2021-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('date_type', models.CharField(max_length=10)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('virtual_interlining', models.BooleanField(default=True)),
                ('exclude_carriers', models.JSONField(blank=True, default=dict, max_length=255)),
            ],
            options={
                'db_table': 'common_parameters',
            },
        ),
    ]
