# Generated by Django 3.1.3 on 2021-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonparameters',
            name='consolidate_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
